### PR TITLE
add match_path option to filter files

### PR DESCRIPTION
**Pull request by rmorshea**
Closes: #11

This adds a `match_path` option which should be a regex pattern matching the path to your files within the `docs_dir`. For example if you had a blog under `docs/blog` where `docs_dir` is `docs` you might use:

```
match_path: "blog/.*"
```

There aren't really very many tests so it's hard to demonstrate that this works. The best I can do is show you that it works on my site:

- Site: https://rmorshea.github.io/
- Source: https://github.com/rmorshea/rmorshea.github.io

# Misc

Also removes IDE config files.

### CODE REVIEW

**Comment by Guts** [comment]
Thanks, it looks good to me.

Before I merge it, could you add it to the configuration page into the docs please?

And please, edit your PR description to mention you removed the IDE configuration files.

**Comment by Guts** [comment]
@rmorshea some questions:

- is it possible to combine multiple paths pattern?
- is it possible to use the an excluding pattern?

**Comment by rmorshea** [comment]
@Guts I think having two different patterns `include_paths` and `exclude_paths` might be useful (this is what `black` does [for example](https://black.readthedocs.io/en/stable/installation_and_usage.html) with `--include` and `--exclude`) however, a regex pattern is definitely powerful enough to match multiple directories.

The following would include everything under `dir_1` and `dir_2` except for `dir_1/sub_1` and `dir_1/sub_2`

```
include_paths: (dir_1|dir_2)/.*
exclude_paths: dir_1/(sub_1|sub_2)/.*
```

**Comment by rmorshea** [comment]
Another thing I'm realizing is that this doesn't normalize the paths. So if you were on windows you'd have to use a different path matching pattern that uses `\` instead. Not too hard though, `pathlib` can do that.

**Comment by Guts** [comment]
> @Guts I think having two different patterns `include_paths` and `exclude_paths` might be useful (this is what `black` does [for example](https://black.readthedocs.io/en/stable/installation_and_usage.html) with `--include` and `--exclude`) however, a regex pattern is definitely powerful enough to match multiple directories.
> 
> The following would include everything under `dir_1` and `dir_2` except for `dir_1/sub_1` and `dir_1/sub_2`
> 
> ```
> include_paths: (dir_1|dir_2)/.*
> exclude_paths: dir_1/(sub_1|sub_2)/.*
> ```

Thanks @rmorshea for your inputs.
I just had black (and precommit) in mind, so I was wondering if you're interesting in proposing something similar here?

**Comment by rmorshea** [comment]
@Guts, I'm a little stretched for time at the moment so I'm not sure when I'll be able to get to this.

**Comment by Guts** [comment]
> @Guts, I'm a little stretched for time at the moment so I'm not sure when I'll be able to get to this.

Ok. So I propose you to merge here until you, me or someone else implement the include/exclude mechanisms.

**Comment by rmorshea** [comment]
Created an issue to track the request for include/exclude patterns.

**Pull request merged**
